### ISSUE TITLE
Query language documentation

### ISSUE THREAD

**Issue by Reza-esfandiarpoor** [wandb/weave#1011]
Hi, is there a reference/documentation for weave query language? There is [this one](https://docs.wandb.ai/ref/weave) which explains the available objects but there is no explanation of the syntax of the language itself like `map`, `filter`, etc.

**Comment by tssweeney** [comment]
Hello @Reza-esfandiarpoor - thank you for your issue. Unfortunately, we have shifted directions away from the dashboards / stream table product to a more opinionated solution for LLM debugging and tracing. If you are curious, please checkout our docs at https://wandb.me/weave. As such, I am going to close this ticket as we are unlikely to continue development against this feature set at the moment. 

Note: if you are using the expression editor in W&B's main app, please reopen as that part of the product is still alive and well.
