### ISSUE TITLE
Weave not working with Flask

### ISSUE THREAD

**Issue by EHxuban11** [wandb/weave#1684]
If a function decorated with weave is called from a Flask endpoint, weave won't work.

CODE:
`from flask import Flask
import os
from groq import Groq
import weave

app = Flask(__name__)

@weave.op()
def groq(user_message: str):
    client = Groq(
    api_key="***",
    )
    chat_completion = client.chat.completions.create(
        messages=[
            {
                "role": "user",
                "content": user_message,
            }
        ],
        model="mixtral-8x7b-32768",
    )
    message = chat_completion.choices[0].message.content
    print(chat_completion.choices[0].message.content)
    return message

@app.route('/groq')
def interact():
    message = "Explain the importance of fast language models"
    return groq(message)

if __name__ == '__main__':
    weave.init("groq_weave")
    #groq("Dime los 10 mejores jugadores del mundo")
    app.run(debug=True)`

**Comment by jwlee64** [comment]
Hi @EHxuban11, I'm going to add a ticket to our backlog to add more docs around flask and fix this issue

**Comment by Pixel-Panda** [comment]
Would be nice to get a CodeSandbox of this. Its been impossible trying to get this repo working.
<img width="1590" alt="image" src="https://github.com/wandb/weave/assets/63879450/c990d54e-7054-4634-99d2-7b710a4f04f4">

**Comment by EHxuban11** [comment]
> Would be nice to get a CodeSandbox of this. Its been impossible trying to get this repo working. <img alt="image" width="1590" src="https://private-user-images.githubusercontent.com/63879450/340118574-c990d54e-7054-4634-99d2-7b710a4f04f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1NTY5NjcsIm5iZiI6MTcxODU1NjY2NywicGF0aCI6Ii82Mzg3OTQ1MC8zNDAxMTg1NzQtYzk5MGQ1NGUtNzA1NC00NjM0LTk5ZDItN2I3MTBhNGYwNGY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDE2NTEwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3NjFhM2M3YTEwZGYzNjRlYzg2ZDRmNmRjNDUwZDFmYjgwZTA3NTUxZTJjOTM1ZDFhOGM3N2UxNTQyMzc1YWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lb0B8hYh6hey9vuuxS7mUe125dO6lFIQt5CMexfBgts">

Hello, 

It works for me in python, maybe this helps you or other people to set up:
`import os
from groq import Groq
import weave

@weave.op()
def groq(user_message: str):
    client = Groq(
    api_key="API_KEY_HERE",
    )

    chat_completion = client.chat.completions.create(
        messages=[
            {
                "role": "user",
                "content": user_message,
            }
        ],
        model="mixtral-8x7b-32768",
    )
    message = chat_completion.choices[0].message.content
    print(chat_completion.choices[0].message.content)
    return message

if __name__ == '__main__':
    weave.init("groq_weave")
    groq("Dime los 10 mejores jugadores de futbol del mundo")
`

**Comment by Pixel-Panda** [comment]
> > Would be nice to get a CodeSandbox of this. Its been impossible trying to get this repo working. <img alt="image" width="1590" src="https://private-user-images.githubusercontent.com/63879450/340118574-c990d54e-7054-4634-99d2-7b710a4f04f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1NTY5NjcsIm5iZiI6MTcxODU1NjY2NywicGF0aCI6Ii82Mzg3OTQ1MC8zNDAxMTg1NzQtYzk5MGQ1NGUtNzA1NC00NjM0LTk5ZDItN2I3MTBhNGYwNGY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDE2NTEwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3NjFhM2M3YTEwZGYzNjRlYzg2ZDRmNmRjNDUwZDFmYjgwZTA3NTUxZTJjOTM1ZDFhOGM3N2UxNTQyMzc1YWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lb0B8hYh6hey9vuuxS7mUe125dO6lFIQt5CMexfBgts">
> 
> Hello,
> 
> It works for me in python, maybe this helps you or other people to set up: `import os from groq import Groq import weave
> 
> @weave.op() def groq(user_message: str): client = Groq( api_key="API_KEY_HERE", )
> 
> ```
> chat_completion = client.chat.completions.create(
>     messages=[
>         {
>             "role": "user",
>             "content": user_message,
>         }
>     ],
>     model="mixtral-8x7b-32768",
> )
> message = chat_completion.choices[0].message.content
> print(chat_completion.choices[0].message.content)
> return message
> ```
> 
> if **name** == '**main**': weave.init("groq_weave") groq("Dime los 10 mejores jugadores de futbol del mundo") `

I ran every command as instructed but i doubt that works in CodeSandbox.Also im not sure what part of this is pasted code without any context as to where it goes is meant to solve the issue I posted. Looks like a pretty generic chat completion pair python script for mixtral.

**Comment by tssweeney** [comment]
Hello all,

Thank you @EHxuban11 for the report and @Pixel-Panda for additional discussion. We have a bigger refactor going on right now to rework some context management which will play nicer with Flask (as well as other environments such as Google Colab). We will update with progress once this work is closer to delivery.

Thank you,
Tim

**Comment by andrewtruong** [comment]
Hey @EHxuban11, this should be addressed with the PR above.  Can you try it out and let us know?  Thanks!

**Comment by Pixel-Panda** [comment]
Per the below, you guys fucking rock. Let me know if you need a good handle on god level UI. That’s my jam, forced into coder due to YT channels using Ai to piss on dreams. Now I know code and get why this didn’t work. But man, aren’t you glad a new wave of kinda-totally-in-no-away-are devs, flooding hot through the community of ‘never suffered this much FML’.  ;)
—-

> Hey [@EHxuban11](https://github.com/EHxuban11), this should be addressed with the PR above. Can you try it out and let us know? Thanks!



> Hello all,
> 
> Thank you [@EHxuban11](https://github.com/EHxuban11) for the report and [@Pixel-Panda](https://github.com/Pixel-Panda) for additional discussion. We have a bigger refactor going on right now to rework some context management which will play nicer with Flask (as well as other environments such as Google Colab). We will update with progress once this work is closer to delivery.
> 
> Thank you, Tim
