### ISSUE TITLE
error when running code in `tutorial-rag`

### ISSUE THREAD

**Issue by xke** [wandb/weave#1724]
I was trying to run the tutorial at https://wandb.github.io/weave/tutorial-rag

Got some errors. Have the fix, will send a PR.

<img width="914" alt="Screenshot 2024-06-06 at 2 38 19 PM" src="https://github.com/wandb/weave/assets/3505778/e9a61dcb-19af-4908-85ba-50018afe79d8">

<img width="907" alt="Screenshot 2024-06-06 at 2 38 49 PM" src="https://github.com/wandb/weave/assets/3505778/5dbfd71c-3d63-433a-bd36-41a059fc8021">

![Screenshot 2024-06-06 at 2 39 46 PM](https://github.com/wandb/weave/assets/3505778/7132a80f-14fc-4b20-a5b5-9afae01a2496)

**Comment by xke** [comment]
Screenshots after fix:

<img width="866" alt="Screenshot 2024-06-06 at 3 18 47 PM" src="https://github.com/wandb/weave/assets/3505778/691e74c1-bc70-4d29-aa2c-998b84523439">

![Screenshot 2024-06-06 at 3 20 06 PM](https://github.com/wandb/weave/assets/3505778/aeb9c6cc-bb06-4027-9ce3-7972ca5081aa)

**Comment by xke** [comment]
Ok, let me know if I should try creating another PR (in case it's difficult to get the other PR unstuck).

**Comment by gtarpenning** [comment]
@xke Nope, you have done everything right, its a process issue on our side. You will be the first to know when its in :)

**Comment by xke** [comment]
@gtarpenning , looks like there are still 4 PR checks that don't run for some reason. I wonder if trying something like this will reset things: https://stackoverflow.com/a/76333176

**Comment by tssweeney** [comment]
Thank you for the PR! I applied and merged your changes here: https://github.com/wandb/weave/pull/1840
