### ISSUE TITLE
Latency is not present in downloaded CSV

### ISSUE THREAD

**Issue by Karthi-PAL** [wandb/weave#1730]
I was trying out weave to log LLM prompts and response and I was trying to do a dashboard from the logs I exported the CSV and the latency column was NaN 😞, Am planning to do a LLM as a service and in that time I need to log all the prompts with its results and also with the user who used as of now the user name for each request is just my name , is there a way the log can be written with the name that I send to the weave trace.

**Comment by gtarpenning** [comment]
Hey @Karthi-PAL, responding to let you know we are aware of empty latency column issue, and is ticketed for triage [here](https://wandb.atlassian.net/browse/WB-19203) (internal link). This is a bug and will be addressed. If it's important for your workflow I can get eyes on it sooner, let me know. 

As for logging the user of each request, I will get back to you with the most idiomatic way of doing this. Thanks for the request!

**Comment by gtarpenning** [comment]
@Karthi-PAL Following up here, logging the name of the requester is best achieved through use of the `attributes` context. 

```
@weave.op
def call_llm(prompt: str, request: str):
    return f"{prompt} {request}"

user = 'user123'
with weave.attributes({'user': user}):
    call_llm('say hi to', user)
```

**Comment by Karthi-PAL** [comment]
> @Karthi-PAL Following up here, logging the name of the requester is best achieved through use of the `attributes` context.
> 
> ```
> @weave.op
> def call_llm(prompt: str, request: str):
>     return f"{prompt} {request}"
> 
> user = 'user123'
> with weave.attributes({'user': user}):
>     call_llm('say hi to', user)
> ```

thanks for the help but one small doubt,it seems like weave runs langchain and flash behind the scenes. From my experience langchain is a small pain they update it's modules very often,at first it gives warning then the obsulte syntax can cause the system the crash with error.


`
UserWarning: Importing BasePromptTemplate from langchain root module is no longer supported. Please use langchain.schema.prompt_template.BasePromptTemplate instead.
  warnings.warn(
`
I get this  warning every time I start my weave code.
