### ISSUE TITLE
OSError: source code not available.

### ISSUE THREAD

**Issue by masterbatcoderman10** [wandb/weave#1809]
I'm trying to run a class method with the decorator added to it, and while it works fine sometimes out of a sudden it is prone to throwing an `OSError: source code not available`.

This error only occurs with the latest version of `weave`, 0.50.5.

**Comment by jamie-rasmussen** [comment]
Thanks for reporting this! If there is a full stack trace could you post it here? And could you tell us a little more information about your environment, e.g. Python version and whether you are running in a notebook or not?

**Comment by tssweeney** [comment]
Adding internal ticket for bug tracker: https://wandb.atlassian.net/browse/WB-19479

**Comment by andrewtruong** [comment]
Hi @masterbatcoderman10 , this should be addressed with the above PR!
