### ISSUE TITLE
GUI issue - no scrollbar in the summary tab

### ISSUE THREAD

**Issue by ArtemPt239** [wandb/weave#2161]
Hello!

I pass quite a lot of attributes in the `with weave.attributes` block.
However, when I click on a `summary` tab of a trace in the wandb web GUI - the attributes don't fit on the same page, and there are no slider to scroll them down. Hence, I can only see a couple of attributes, but not all of them (see the pic - there are much more fields in the `config` dictionary, but only a small subset of them is shown)

![img](https://github.com/user-attachments/assets/9df34751-fc37-494f-86c8-1c49434df83a)

I think adding the option to scroll the summary tab of a trace view would be great.

**Comment by jamie-rasmussen** [comment]
Hello, a fix is in review, and I expect it to be available in production within the next day or so. Thank you very much for reporting this issue to us!
