### ISSUE TITLE
RuntimeError: Python version 2.6 or 2.7 required.

### ISSUE THREAD

**Issue by aris-t** [wandb/weave#23]
I just tried the pip install and keep getting this. Both pip and pip3.

```
user@book:~$ pip3 install weave
Defaulting to user installation because normal site-packages is not writeable
Collecting weave
  Using cached weave-0.17.0.tar.gz (573 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-8744l1w4/weave_f9103c924690420e88b945d4d2312c8a/setup.py", line 24, in <module>
          raise RuntimeError("Python version 2.6 or 2.7 required.")
      RuntimeError: Python version 2.6 or 2.7 required.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
```
$ python --version
Python 3.8.10
```

Any ideas. Mostly posting for others to reference.

**Comment by aris-t** [comment]
So the answer is read the installation guide and make sure your python is greater than 3.9. No idea why the above issue has that assert string about python 2.x.

I will let someone else close hopefully answering the python 2.x issue?

**Comment by adrnswanberg** [comment]
My guess is that older versions of python confuse this weave package with older versions of scipy-weave (https://github.com/scipy/weave/blob/518fdf35a048d18b370c8fc2c2b036fb8e226132/setup.py#LL24C62-L24C62)

Thanks for giving Weave a try and for documenting this issue for other new users!

**Comment by pandya6988** [comment]
I still have this issue. How did you solve this problem?

**Comment by vanpelt** [comment]
@pandya6988 what's the output of `python --version` on your system.  You'll need to be running atleast python 3.9 to install weave.  You can use a tool like [pyenv](https://github.com/pyenv/pyenv) to manage multiple versions of python on your system.

**Comment by pandya6988** [comment]
python3.9 with following command solved the problem. 
`python -m pip install weave`

Thanks :)
