### ISSUE TITLE
How to customize the running name of Evaluations

### ISSUE THREAD

**Issue by madroidmaq** [wandb/weave#2331]
How to customize the running name of Evaluations. The current default value is Evaluations.evaluate. How should I customize this value in the py code? My current method of operation is to manually edit it on the H5 page.

**Comment by jwlee64** [comment]
Hi @madroidmaq, 

To customize the display name of a call of eval you can

    ```python showLineNumbers
    import weave

    # Initialize the client
    client = weave.init("your-project-name")

    # Get a specific call by its ID
    call = client.get_call("call-uuid-here")

    # Set the display name of the call
    call.set_display_name("My Custom Display Name")
    ```
    
  Let me know if that answers your question or if you need anything else.

**Comment by madroidmaq** [comment]
@jwlee64 Thank you for your reply.

The code I use to evaluate the dataset is roughly as follows. How should I obtain the `call_id` information corresponding to the current evaluation?

```py
def run_eval():
  
    image_model = FoodImageWorkflowModel(
        system_prompt=system_prompt,
        version=run_version,
        ....
    )

    evaluation = Evaluation(
        name='food_image',
        dataset=datas,
        scorers=[
            FoodScorer(output_file=output_file)
        ],
    )

    client = weave.init('food-eval')
    asyncio.run(evaluation.evaluate(image_model))

    print(f"image_model:\n{image_model}")
```

**Comment by jwlee64** [comment]
Hi @madroidmaq 

Sadly there is no way to prettily get the last call of the evaluation and set the display name. I am going to ticket these 2 things and raise to the team. 
1. Get call id of evaluation.evaluate in summary object
2. Set display name of evaluation on evaluate

I do have a code snippet that should hopefully unblock. 
Because evaluate within the Evaluation object is an op, we can get the calls of that op, and sort for the most recently called. 

```python
# Define the evaluation
evaluation = Evaluation(name="cool_eval", dataset=examples, scorers=[match_score1])

# Init
client = weave.init("simple_eval")

# Run the evaluation
eval_result = asyncio.run(evaluation.evaluate(function_to_evaluate))

# Get the ref uri of the evaluation
op_uri = evaluation.evaluate.ref.uri()
username = "jwlee64"  # add your username

# Get calls of the evaluation sorting for most recent, limit 1
calls = client.server.calls_query(
    {
        "project_id": f"{username}/simple_eval",
        "filter": CallsFilter(op_names=[op_uri]),
        "sort_by": [{"field": "started_at", "direction": "desc"}],
        "limit": 1,
    }
)

# Get the most recent call
call = client.get_call(calls.calls[0].id)

# Set the display name of the call
call.set_display_name("My Custom Display Name")
```

Hopefully this helps

**Comment by madroidmaq** [comment]
hi @jwlee64 ，its worked for me，thanks.

Looking forward to the improvements you mentioned to subsequent APIs.
