### ISSUE TITLE
[bug] Datasets with CJK names & Evaluation comparisons with those datasets not displaying in UI

### ISSUE THREAD

**Issue by TeoZosa** [wandb/weave#2567]
This was a weird one I ran into. At first I thought it was from datasets being too large[^1], but the problem stuck around even at smaller dataset sizes that work fine with English names. Hopefully the patch for this one isn't too much work. 

[^1]: #2566

## Steps to reproduce

```python
>>> import weave
>>> weave.init(project_name="my-project")
>>> for name in ["Deep Learning", "深度學習", "深層学習", "딥 러닝"]:
...     dataset = weave.Dataset(name=name, rows=[{"key": "value"}])
...     weave.publish(dataset)
📦 Published to https://wandb.ai/...
ObjectRef(entity='...', project='...', name='Deep-Learning', digest='...', extra=())
📦 Published to https://wandb.ai/...
ObjectRef(entity='...', project='...', name='深度學習', digest='...', extra=())
📦 Published to https://wandb.ai/...
ObjectRef(entity='...', project='...', name='深層学習', digest='...', extra=())
📦 Published to https://wandb.ai/...
ObjectRef(entity='...', project='...', name='딥-러닝', digest='...', extra=())
```

### `Dataset`
Datasets are confirmed loadable via the API

```python
>>> import weave
>>> import weave.trace.weave_client
>>> weave.init(project_name="my-project")
>>> def fetch_dataset(dataset_ref: str) -> weave.Dataset:
...     dataset_ref_sanitized = weave.trace.weave_client.sanitize_object_name(dataset_ref)
...     dataset = weave.ref(dataset_ref_sanitized).get()
...     return dataset
>>> for name in ["Deep Learning", "深度學習", "深層学習", "딥 러닝"]:
...    print(f"{name}: {len(fetch_dataset(name).rows)}")
Deep Learning: 1
深度學習: 1
深層学習: 1
딥 러닝: 1  
```

But not viewable in the UI

<details> <summary> Click here for screenshots </summary> 

<img width="857" alt="Screenshot 2024-10-02 at 10 03 56" src="https://github.com/user-attachments/assets/84a0fb51-f3b9-45eb-8cd7-2267a11beba6">
<img width="857" alt="Screenshot 2024-10-02 at 10 01 55" src="https://github.com/user-attachments/assets/1cc50036-be5f-450b-a5c7-daef1bf45ad0">
<img width="857" alt="Screenshot 2024-10-02 at 10 01 50" src="https://github.com/user-attachments/assets/2d49b3ed-89e5-4ae6-9fc8-e13c09ef2e9c">
<img width="857" alt="Screenshot 2024-10-02 at 10 01 52" src="https://github.com/user-attachments/assets/34af393b-8b2b-4e37-8492-a7bdb6abdc08">

</details>

### `Evaluation`

The Evaluation comparison view tries to load and eventually errors-out

<details> <summary> Click here for screenshots </summary> 

<img width="1659" alt="Screenshot 2024-10-02 at 9 51 55" src="https://github.com/user-attachments/assets/df6ca174-4d6b-4a00-93c2-77034d6e530c">

<img width="674" alt="Screenshot 2024-10-02 at 9 51 40" src="https://github.com/user-attachments/assets/7b851ed6-f4f5-42b0-abb5-0b413b9eb5b0">

</details>

**Comment by jamie-rasmussen** [comment]
Thank you very much for this and your other recent submissions, we are investigating.

**Comment by TeoZosa** [comment]
Sounds good; thanks for jumping on this so quickly, @jamie-rasmussen!

**Comment by jamie-rasmussen** [comment]
Tracking internally as https://wandb.atlassian.net/browse/WB-21343

**Comment by tssweeney** [comment]
Hello - we have identified a fix and will deploy this week: https://github.com/wandb/weave/commit/483ae6827af6c4bf19485547354f1d5aa0143bd1. This is actually a read-only issue and previously logged data should be correct.
