### ISSUE TITLE
Trace captures incorrect input when running evaluation

### ISSUE THREAD

**Issue by kdaniel21** [wandb/weave#2669]
I only got started with the tool today, so there is a fair chance that I might have missed something. However, it seems like in the latest version (`0.51.14`), when running an evaluation, all of the traces "capture" the same input value. 
- When you look at the traces, all traces have the same input value (the output is normal/different).
- As a further consequence, when looking at the evaluation in the Comparison view, there is only a single entry in the `Output comparison` view. The other "values" are added as different "trials" (despite settings `trials=1` when creating the evaluation - this is probably because the input is the same).

First I thought that I had messed up something with the parallelization/I had a race condition, because the input was always the last evaluation input. Still, after a few hours, downgrading to `0.51.12` worked perfectly. If you cannot reproduce it or anything is unclear, let me know and I'll try to create a reproduction.

**Comment by tssweeney** [comment]
Hello @kdaniel21 thank you for the report. Do you mind sharing code that produces this error? Also, can you share your current python version?

**Comment by tssweeney** [comment]
I was able to reproduce this locally. Please allow an hour or so for investigation

**Comment by kdaniel21** [comment]
Thank you for the quick help @tssweeney!
