### ISSUE TITLE
How to customize the parallel number of evaluations

### ISSUE THREAD

**Issue by madroidmaq** [wandb/weave#3188]
I'm not sure if there is already a way to customize the number of concurrent operations. From the logs, we can see that currently Weave performs concurrent evaluations. The issue we are currently facing is that if there are a large number of requests at the same time, it may trigger errors due to the token limit. Therefore, I want to control the number of concurrent operations in this part, but I did not find a description of this in the documentation.

```
Evaluated 863 of 967 examples
Evaluated 864 of 967 examples
Evaluated 865 of 967 examples
Evaluated 866 of 967 examples
Evaluated 867 of 967 examples
Evaluated 868 of 967 examples
Evaluated 869 of 967 examples
Evaluated 870 of 967 examples
Evaluated 871 of 967 examples
Evaluated 872 of 967 examples
Evaluated 873 of 967 examples
Evaluated 874 of 967 examples
Evaluated 875 of 967 examples
Evaluated 876 of 967 examples
Evaluated 877 of 967 examples
Evaluated 878 of 967 examples
Evaluated 879 of 967 examples
```

**Comment by jamie-rasmussen** [comment]
Sometimes the async execution of Evaluations will trigger a rate limit on the models of OpenAI, Anthropic, etc. To prevent that you can set an environment variable to limit the amount of parallel workers e.g. `WEAVE_PARALLELISM=3`

There is a mention of this in the docs but it is easy to miss:
https://weave-docs.wandb.ai/tutorial-rag#4-pulling-it-all-together
I will file an internal note with our docs team.

Please let us know if that doesn't resolve your issue and thanks for using Weave!
