### ISSUE TITLE
FileExistsError in window 10

### ISSUE THREAD

**Issue by ravinsharma7** [wandb/weave#42]
I'm running in conda Python 3.9.16, windows 10. 

installed weave using this command(installed pip in conda env)
```
pip install weave
```

I tried the example
```
import weave
# ... use any existing dataframe, here we load the iris dataframe
from sklearn.datasets import load_iris
df = load_iris(as_frame=True).data

weave.show(df)
```

Am getting this error.

---------------------------------------------------------------------------
FileExistsError                           Traceback (most recent call last)
Cell In[3], line 1
----> 1 weave.show(df)

File [e:\Project\weave\.conda\lib\site-packages\weave\show.py:141](file:///E:/Project/weave/.conda/lib/site-packages/weave/show.py:141), in show(obj, height)
    138     obj = ops.dataframe_to_arrow(obj)
    140 usage_analytics.show_called()
--> 141 panel_url = show_url(obj)
    143 iframe = IFrame(panel_url, "100%", "%spx" % height, ['allow="clipboard-write"'])
    144 display(iframe)

File [e:\Project\weave\.conda\lib\site-packages\weave\show.py:107](file:///E:/Project/weave/.conda/lib/site-packages/weave/show.py:107), in show_url(obj)
    106 def show_url(obj=None):
--> 107     params = _show_params(obj)
    108     panel_url = f"{context.get_frontend_url()}?fullScreen"
    109     if "weave_node" in params:

File [e:\Project\weave\.conda\lib\site-packages\weave\show.py:85](file:///E:/Project/weave/.conda/lib/site-packages/weave/show.py:85), in _show_params(obj)
     83 def _show_params(obj):
     84     # Get a weave node (expression) that will return the object, and something to call it
---> 85     node, var_name = make_show_obj(obj)
     87     # Place the node inside a root group, so the user can add panels.
     88     ui_root = make_container(node, var_name)
...
    511 temp_path = os.path.join(d, tmp_path_name)
    512 os.symlink(target_path, temp_path)
--> 513 os.rename(temp_path, symlink_path)

FileExistsError: [WinError 183] Cannot create a file when that file already exists: '\\tmp\\weave\\fs\\admin\\local-artifacts\\tmp\\tmphg5bnw6l\\tmplink-ZDVTG1ISLKKD' -> '/tmp\\weave\\fs\\admin\\local-artifacts\\obj\\latest'
Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?e4dd22cb-c2fa-4a92-bb99-985dc9f309f9) or open in a [text editor](command:workbench.action.openLargeOutput?e4dd22cb-c2fa-4a92-bb99-985dc9f309f9). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...

**Comment by tssweeney** [comment]
Hello - thank you for your issue. This part of the product is no longer in development and as such I am going to close this issue. We can reopen if applicable in the future.
