### ISSUE TITLE
'weave.environment' Error while running the basic Example

### ISSUE THREAD

**Issue by zshareef** [wandb/weave#486]
I am using the "weave" in my local environment in MacBook M1.

I am using the following example:

```
import weave

from sklearn.datasets import load_iris

def get_iris_dataset():
    iris = load_iris(as_frame=True)
    data = iris['data']
    data['target_id'] = iris['target']
    data['target_name'] = iris['target_names'][iris['target']]

    def clean_column_name(c):
        return c.replace(" (cm)", "").replace(" ", "_")
    data.columns = [clean_column_name(c) for c in data.columns]
    return data

iris_df = get_iris_dataset()
weave.show(iris_df)
```

It is very simple and basic example. I am getting the following error on running this example:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[11], line 1
----> 1 weave.show(iris_df)

File /opt/homebrew/lib/python3.11/site-packages/weave/show.py:141, in show(obj, height)
    138 if util.is_pandas_dataframe(obj):
    139     obj = ops.dataframe_to_arrow(obj)
--> 141 panel_url = show_url(obj)
    143 if util.is_colab():
    144     from google.colab.output import serve_kernel_port_as_iframe

File /opt/homebrew/lib/python3.11/site-packages/weave/show.py:115, in show_url(obj)
    113 if os.environ.get("WEAVE_FRONTEND_DEVMODE"):
    114     context.use_frontend_devmode()
--> 115 params = _show_params(obj)
    116 panel_url = f"{context.get_frontend_url()}?fullScreen"
    117 if "weave_node" in params:

File /opt/homebrew/lib/python3.11/site-packages/weave/show.py:86, in _show_params(obj)
     84 def _show_params(obj):
     85     # Get a weave node (expression) that will return the object, and something to call it
---> 86     node, var_name = make_show_obj(obj)
     88     # Place the node inside a root group, so the user can add panels.
     89     ui_root = make_container(node, var_name)

File /opt/homebrew/lib/python3.11/site-packages/weave/show.py:75, in make_show_obj(obj)
     72     names = util.find_names(obj)
     74     ref = storage.save(obj, name=names[-1])
---> 75     node = ops.get(ref.uri)
     76     return node, make_varname_for_type(ref.type)
     78 raise errors.WeaveTypeError(
     79     "%s not yet supported. Create a weave.Type to add support." % type(obj)
     80 )

File /opt/homebrew/lib/python3.11/site-packages/weave/op_def.py:294, in OpDef.__call__(_self, *args, **kwargs)
    292     return _self.eager_call(*args, **kwargs)
    293 else:
--> 294     return _self.lazy_call(*args, **kwargs)

File /opt/homebrew/lib/python3.11/site-packages/weave/op_def.py:327, in OpDef.lazy_call(_self, *args, **kwargs)
    323 with tracer.trace("refine.%s" % _self.uri):
    324     # api's use auto-creates client. TODO: Fix inline import
    325     from . import api
--> 327     final_output_type = api.use(called_refine_output_type)  # type: ignore
    328 if final_output_type == None:
    329     # This can happen due to nullability. In that case, accept the output type is null
    330     final_output_type = types.NoneType()

File /opt/homebrew/lib/python3.11/site-packages/weave/api.py:72, in use(nodes, client)
     71 def use(nodes, client=None):
---> 72     usage_analytics.use_called()
     73     if client is None:
     74         client = _context.get_client()

File /opt/homebrew/lib/python3.11/site-packages/weave/usage_analytics.py:45, in use_called()
     44 def use_called():
---> 45     track("called use")

File /opt/homebrew/lib/python3.11/site-packages/weave/usage_analytics.py:33, in track(action, info)
     32 def track(action: str, info=None):
---> 33     if not analytics_enabled():
     34         return
     35     try:

File /opt/homebrew/lib/python3.11/site-packages/weave/usage_analytics.py:27, in analytics_enabled()
     25 def analytics_enabled():
     26     context_enabled = context_state.analytics_enabled()
---> 27     env_enabled = environment.usage_analytics_enabled
     29     return context_enabled and env_enabled

AttributeError: module 'weave.environment' has no attribute 'usage_analytics_enabled'
```

weave : 0.26.0
Python : 3.11.4
notebook : 7.0.2
jupyterlab : 4.0.4

**Comment by dannygoldstein** [comment]
@zshareef Sorry you hit this! How did you install `weave`? v0.26.0 has `usage_analytics_enabled` defined here: 

https://github.com/wandb/weave/blob/3f03027ff2b156b599dc705ba9fa9067f9e09e9d/weave/environment.py#L217

It should be being called as a function instead of being accessed as an attribute. I just put up a PR to fix this: 

https://github.com/wandb/weave/pull/518

**Comment by zshareef** [comment]
> @zshareef Sorry you hit this! How did you install `weave`? v0.26.0 has `usage_analytics_enabled` defined here:

@dannygoldstein ... I installed the weave using pip (https://pypi.org/project/weave/).

Thanks for creating the PR.

**Comment by tssweeney** [comment]
Hi @zshareef I am attempting to recreate your issue but having problems. I am also on an M1 locally - using a fresh install of Python 3.11.4 and weave in an isolated environment. I also pinned the other requirements exactly as you have them. Even so the example is working for me:

<img width="647" alt="Screenshot 2023-09-05 at 10 43 56" src="https://github.com/wandb/weave/assets/2142768/8aac7754-7b17-4156-93fb-c4cbe5afb5c1">

Can you share the results of:
a) `pip freeze`
b) Exactly how you are starting your jupyter environment?

**Comment by zshareef** [comment]
The output of the `pip freeze` is below:

absl-py==1.4.0
adlfs==2023.8.0
aiobotocore==2.5.4
aiofiles==23.1.0
aiohttp==3.8.4
aiohttp-cors==0.7.0
aioitertools==0.11.0
aioprocessing==2.0.1
aiorwlock==1.3.0
aiosignal==1.3.1
analytics-python==1.2.9
anyio==3.7.1
appdirs==1.4.4
appnope==0.1.3
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
Arpeggio==2.0.0
array-record==0.4.0
arrow==1.2.3
asttokens==2.2.1
astunparse==1.6.3
async-lru==2.0.4
async-timeout==4.0.2
attrs==22.2.0
azure-core==1.29.1
azure-datalake-store==0.0.53
azure-identity==1.14.0
azure-storage-blob==12.17.0
Babel==2.12.1
backcall==0.2.0
backoff==2.2.1
beautifulsoup4==4.12.2
binaryornot==0.4.4
black==23.7.0
bleach==6.0.0
blessed==1.20.0
blinker==1.6.2
botocore==1.31.17
cachetools==5.3.1
certifi==2023.5.7
cffi==1.15.1
chardet==5.2.0
charset-normalizer==3.2.0
clearml==1.12.2
clearml-agent==1.5.2
click==8.1.4
cloudpickle==2.2.1
colorful==0.5.5
comm==0.1.4
contourpy==1.1.0
cookiecutter==2.3.0
croniter==1.4.1
cryptography==41.0.3
cycler==0.11.0
dataclasses-json==0.5.9
debugpy==1.6.7
decorator==5.1.1
defusedxml==0.7.1
Deprecated==1.2.14
dill==0.3.6
diskcache==5.6.1
distlib==0.3.7
dm-tree==0.1.8
docker==6.1.3
docker-image-py==0.1.12
docker-pycreds==0.4.0
docstring-parser==0.15
etils==1.3.0
executing==1.2.0
fastapi==0.101.0
fastjsonschema==2.18.0
filelock==3.12.0
Flask==2.3.2
Flask-Cors==4.0.0
flatbuffers==23.5.26
flyteidl==1.5.15
flytekit==1.8.3
flytekitplugins-pod==1.8.3
fonttools==4.42.0
fqdn==1.5.1
frozenlist==1.4.0
fsspec==2023.6.0
furl==2.1.3
gast==0.4.0
gcsfs==2023.6.0
gitdb==4.0.10
GitPython==3.1.32
google-api-core==2.11.1
google-auth==2.22.0
google-auth-oauthlib==1.0.0
google-cloud-core==2.3.3
google-cloud-storage==2.10.0
google-crc32c==1.5.0
google-pasta==0.2.0
google-resumable-media==2.5.0
googleapis-common-protos==1.59.1
gpustat==1.1
gql==3.4.1
graphql-core==3.2.3
grpcio==1.53.0
grpcio-status==1.53.0
h11==0.14.0
h5py==3.9.0
idna==3.4
importlib-metadata==6.8.0
importlib-resources==6.0.0
iniconfig==2.0.0
install==1.3.5
ipykernel==6.25.0
ipynbname==2023.2.0.0
ipython==8.14.0
isodate==0.6.1
isoduration==20.11.0
itsdangerous==2.1.2
janus==1.0.0
jaraco.classes==3.3.0
jedi==0.19.0
Jinja2==3.1.2
jmespath==1.0.1
joblib==1.3.1
json5==0.9.14
jsonpointer==2.4
jsonschema==4.19.0
jsonschema-specifications==2023.7.1
jupyter-events==0.7.0
jupyter-lsp==2.2.0
jupyter_client==8.3.0
jupyter_core==5.3.1
jupyter_server==2.7.0
jupyter_server_terminals==0.4.4
jupyterlab==4.0.4
jupyterlab-pygments==0.2.2
jupyterlab_server==2.24.0
keras==2.13.1
keyring==24.2.0
kiwisolver==1.4.4
kubernetes==27.2.0
libclang==16.0.0
lightgbm==4.0.0
lightning-utilities==0.9.0
llvmlite==0.40.1
Markdown==3.4.3
markdown-it-py==3.0.0
MarkupSafe==2.1.3
marshmallow==3.20.1
marshmallow-enum==1.5.1
marshmallow-jsonschema==0.13.0
matplotlib==3.7.2
matplotlib-inline==0.1.6
mdurl==0.1.2
mistune==3.0.1
more-itertools==10.1.0
mpmath==1.3.0
msal==1.23.0
msal-extensions==1.0.0
msgpack==1.0.5
multidict==6.0.4
mypy-extensions==1.0.0
natsort==8.4.0
nbclient==0.8.0
nbconvert==7.7.3
nbformat==5.9.2
nest-asyncio==1.5.7
networkx==3.1
notebook==7.0.2
notebook_shim==0.2.3
numba==0.57.1
numpy==1.24.3
nvidia-ml-py==12.535.77
oauthlib==3.2.2
objgraph==3.6.0
onnx==1.14.0
opencensus==0.11.2
opencensus-context==0.1.3
opt-einsum==3.3.0
orderedmultidict==1.0.1
overrides==7.4.0
packaging==23.1
pandas==1.5.3
pandocfilters==1.5.0
parso==0.8.3
parver==0.4
pathlib==1.0.1
pathlib2==2.3.7.post1
pathspec==0.11.2
pathtools==0.1.2
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.5.0
platformdirs==3.10.0
plotly==5.15.0
pluggy==1.0.0
portalocker==2.7.0
prometheus-client==0.17.1
promise==2.3
prompt-toolkit==3.0.39
protobuf==4.23.4
protoc-gen-swagger==0.1.0
psutil==5.9.5
ptyprocess==0.7.0
pulumi==3.73.0
pulumi-aws==5.41.0
pulumi-eks==1.0.2
pulumi-gcp==6.62.0
pulumi-kubernetes==3.30.0
pulumi-random==4.13.2
pure-eval==0.2.2
py-spy==0.3.14
pyarrow==10.0.1
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycparser==2.21
pydantic==1.10.12
Pygments==2.16.1
PyJWT==2.4.0
pynndescent==0.5.10
pyOpenSSL==23.2.0
pyparsing==3.0.9
pytest==7.3.1
python-dateutil==2.8.2
python-json-logger==2.0.7
python-slugify==8.0.1
pytimeparse==1.1.8
pytorch-lightning==2.0.5
pytz==2023.3
PyYAML==6.0.1
pyzmq==25.1.0
ray==2.6.3
referencing==0.30.2
regex==2023.8.8
requests==2.28.2
requests-oauthlib==1.3.1
requests-toolbelt==0.10.1
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rich==13.5.2
rich-click==1.6.1
rpds-py==0.9.2
rsa==4.9
s3fs==2023.6.0
scikit-learn==1.3.0
scipy==1.11.1
semver==2.13.0
Send2Trash==1.8.2
sentry-sdk==1.28.0
setproctitle==1.3.2
six==1.16.0
smart-open==6.3.0
smmap==5.0.0
sniffio==1.3.0
sortedcontainers==2.4.0
soupsieve==2.4.1
stack-data==0.6.2
starlette==0.27.0
statsd==3.3.0
subprocess.run==0.0.8
sympy==1.12
tenacity==8.2.2
tensorboard==2.13.0
tensorboard-data-server==0.7.1
tensorboardX==2.6.2
tensorflow==2.13.0
tensorflow-datasets==4.9.2
tensorflow-estimator==2.13.0
tensorflow-macos==2.13.0
tensorflow-metadata==1.13.1
termcolor==2.3.0
terminado==0.17.1
text-unidecode==1.3
threadpoolctl==3.1.0
tinycss2==1.2.1
toml==0.10.2
torch==2.0.1
torchmetrics==1.0.0
torchvision==0.15.2
tornado==6.3.2
tqdm==4.65.0
traitlets==5.9.0
tune-sklearn==0.4.6
typing-inspect==0.9.0
typing_extensions==4.5.0
tzdata==2023.3
umap-learn==0.5.3
uri-template==1.3.0
urllib3==1.26.16
uvicorn==0.23.2
virtualenv==20.21.0
wandb==0.15.8
wcwidth==0.2.6
weave==0.26.0
webcolors==1.13
webencodings==0.5.1
websocket-client==1.6.1
Werkzeug==2.3.6
wrapt==1.15.0
xgboost==1.7.6
xgboost-ray==0.1.17
yarl==1.9.2
zipp==3.16.0

**Comment by zshareef** [comment]
After the PR #518, everything is working for me as well.

**Comment by zshareef** [comment]
After the PR #518 the examples are working fine for me.
