### ISSUE TITLE
weave.monitoring.openai does not support documented openai api_key setting

### ISSUE THREAD

**Issue by binarycrayon** [wandb/weave#664]
Official documented openai sdk support setting the api_key
```
openai.api_key = os.getenv("OPENAI_API_KEY")
```
https://platform.openai.com/docs/api-reference/authentication

this does not seem to be supported properly as implemented in
https://github.com/wandb/weave/blob/master/weave/monitoring/openai.py#L39C1-L54C33

i.e. setting the key `openai.api_key` does not work, it has to be 
```
            response = openai.ChatCompletion.create(
                api_key=os.getenv("OPENAI_API_KEY"),
```

Please support the original behaviour of openai SDK use

**Comment by vanpelt** [comment]
Hey @binarycrayon we support all modes of passing the api key.  The 3rd code example on the official openai docs you linked to show's setting `openai.api_key`.  What specific problem are you running up against?

**Comment by binarycrayon** [comment]
I got error says openai api key is not set despite the fact that I have it both as environment variable `OPENAI_API_KEY` as well as having a statement `openai.api_key = ...`

passing `api_key` as a kwarg to `ChatCompletion.create` resolves that error.

**Comment by vanpelt** [comment]
weird, can you share some basic code that replicates the issue and the version of openai you used so we can try to debug?

**Comment by vanpelt** [comment]
weird, can you share some basic code that replicates the issue and the version of openai you used so we can try to debug?

**Comment by binarycrayon** [comment]
Did both setting environ `OPENAI_API_KEY` as well as the following

from weave.monitoring import openai, init_monitor
openai.api_key = "..."

Have you tried to reproduce it?

**Comment by tssweeney** [comment]
Hello - thank you for your issue. This has been addressed in the latest version.
