### ISSUE TITLE
init_monitor give 403 If I set stream to team space 

### ISSUE THREAD

**Issue by binarycrayon** [wandb/weave#721]
Based on the example, the stream is in the form of 
`<wandb_team_or_user>/<wandb_project>/<stream_name>`. 

I used `https://api.wandb.ai"` as WANDB_BASE_URL and my wandb account API, then set my stream

`my_username/project/name` it works

but gets 403 if I set stream to

`wandb_team/project/name` 

Is this expected?

**Comment by tssweeney** [comment]
Hello @binarycrayon. Please checkout our latest docs at https://wandb.me/weave. We have completely rewritten the application and underlying architecture. It is very likely that this issue is resolved with the latest package and apis.
