### ISSUE TITLE
Does not support ChatCompletion.acreate

### ISSUE THREAD

**Issue by mc-marcocheng** [wandb/weave#762]

**Comment by jlzhao27** [comment]
hey, thanks for the report! We will be working on this shortly and should have it in the next week or 2.

**Comment by tssweeney** [comment]
Hello @mc-marcocheng  Please checkout our latest docs at https://wandb.me/weave. We have completely rewritten the application and underlying architecture. It is very likely that this issue is resolved with the latest package and apis (:
