### ISSUE TITLE
Extend Streaming Table | For Dimensionality Reduction | Download last 1000 entries from Streaming Table for computing

### ISSUE THREAD

**Issue by BenSpex** [wandb/weave#808]
I really love the feature of plotting my embeddings, especially in combination with Streaming Tables. 

However the maximum of 50 dimensions is a limitation: 

![image](https://github.com/wandb/weave/assets/52712273/0c5a0eb8-c654-46b3-8538-5b941d97ac1e)
 from [here](https://docs.wandb.ai/guides/app/features/panels/weave/embedding-projector#plotting-options) 
 
 Is there a way to download the data from the streaming table and either create a new table or extend the table with the projection dimensions. 
 
 So the workflow could be as follow. 

-  Log Data to streaming table (embedding higher much bigger than 50) 
- On a rolling basis, compute the dimensionality reduction on the full embedding for the last 1000 entries.
- Either extend or create a new streaming table with the reduced dimension for display and further processing. 

Yes I could save the data somewhere else and then process them. 
But I already log them in the streaming table, so all of this is already setup and I do not want to double anything.

**Comment by tssweeney** [comment]
Hello @BenSpex , thank you for your issue report. Unfortunately, we have shifted directions away from the dashboards / stream table product to a more opinionated solution for LLM debugging and tracing. If you are curious, please checkout our docs at https://wandb.me/weave. As such, I am going to close this ticket as we are unlikely to continue development against this feature set at the moment.
