### ISSUE TITLE
Feature request | Box Plot Violin Chart

### ISSUE THREAD

**Issue by BenSpex** [wandb/weave#821]
It would be awesome to get something like this 

![image](https://github.com/wandb/weave/assets/52712273/149f72ef-611c-4860-8a08-8d6634c3750f)

![image](https://docs.wandb.ai/assets/images/bar_plots-2dad4e1d885ce162339078fc82fe359e.gif)  

As it is already in [WandB](https://docs.wandb.ai/guides/app/features/panels/bar-plot) 
I assume that it should be possible somehow. 

Thanks

**Comment by tssweeney** [comment]
Hello @BenSpex , thank you for your issue report. Unfortunately, we have shifted directions away from the dashboards / stream table product to a more opinionated solution for LLM debugging and tracing. If you are curious, please checkout our docs at https://wandb.me/weave. As such, I am going to close this ticket as we are unlikely to continue development against this feature set at the moment.
