### ISSUE TITLE
ImportError in OpenAI Python Package Version 1.3 with Weave Monitoring Integration

### ISSUE THREAD

**Issue by Slyracoon23** [wandb/weave#907]
### Environment
- OpenAI Python Package Version: 1.3
- Operating System: Manjaro Linux (Kernel: 6.1.55-1-MANJARO)
- Python Version: 3.10.13
- Weave Version: 0.30.0

### Issue
An ImportError occurs when running the the script for integrating OpenAI with Weave Monitoring, using OpenAI Python package version 1.3.

```
import json
# from openai import OpenAI
# from itertools import chain
import wandb
wandb.login()
import weave
import os
WANDB_BASE_URL = "https://api.wandb.ai"
os.environ["WANDB_BASE_URL"] = WANDB_BASE_URL


WB_PROJECT = "llmon" # top-level directory for this work
STREAM_NAME = "openai_logs" # record table which stores the logs of OpenAI API calls as they stream in
WB_ENTITY = "" # optional: wandb username or team name


from weave.monitoring import openai, init_monitor
m = init_monitor(f"{WB_ENTITY}/{WB_PROJECT}/{STREAM_NAME}")
```
### Error Details
The following error is encountered upon script execution:
```
 File "/home/slyracoon23/miniconda3/envs/openai-wb/lib/python3.10/site-packages/weave/monitoring/openai.py", line 3, in <module>
    from openai import util as openai_util
ImportError: cannot import name 'util' from 'openai' (/home/slyracoon23/miniconda3/envs/openai-wb/lib/python3.10/site-packages/openai/__init__.py)
```

**Comment by tssweeney** [comment]
Hello @Slyracoon23, please checkout out latest docs at wandb.me/weave! We have completely rewritten the logging architecture and application layer. We would love to get your feedback! The APIs are new and much simpler. I am going to close this issue as it references a legacy code path that is no longer in play.
