### ISSUE TITLE
FetchError: invalid json response body at reason: Unexpected token '', "�"... is not valid JSON

### ISSUE THREAD

**Issue by seonglae** [wandb/weave#923]
```
FetchError: invalid json response body at https://proxy.wandb.ai/proxy/openai/v1/chat/completions reason: Unexpected token '', "�"... is not valid JSON
```

Is it nor supported yet from `openai-node` from npm?

I tried `Monitor OpenAI API usage` template by changing `token` and `baseURL`

**Comment by tssweeney** [comment]
Hello @seonglae ,  please checkout our latest docs at https://wandb.me/weave. We have completely rewritten the application and underlying architecture. It is very likely that this issue is resolved with the latest package and apis (:
